<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="C02HF6Z0Q6L5" failures="1" tests="2" name="Submit Test" time="0.089" errors="0" timestamp="2022-12-24T00:25:06 IST">
  <testcase classname="testing.SubmitTest" name="SubmitOrder" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.NullPointerException">
      <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException
at java.base/java.io.File.<init>(File.java:278)
at testing.TestComponents.BaseTest.getJsonDataToMap(BaseTest.java:63)
at testing.SubmitTest.GetData(SubmitTest.java:89)
... 19 more
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- SubmitOrder -->
  <testcase classname="testing.SubmitTest" name="OrderHistoryTest" time="0.0">
    <skipped/>
  </testcase> <!-- OrderHistoryTest -->
</testsuite> <!-- Submit Test -->
